---
jenkins:
  build: ./jenkins
  volumes:
    - ./data/jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1
    - /usr/bin/docker:/usr/bin/docker
  ports:
    - "8080:8080"

registry:
  build: ./registry
  ports:
    - 5000:5000
  volumes:
    - ./data/registry:/registry
  environment:
#    - SETTINGS_FLAVOR=s3
#    - AWS_BUCKET=acme-docker
    - STORAGE_PATH=/registry
#    - AWS_KEY=AKIAHSHB43HS3J92MXZ
#    - SECRET=xdDowwlK7TJajV1Y7EoOZrmuPEJlHYcNP2k4j49T
#    - SEARCH_BACKEND=sqlalchemy
