---
jenkins:
  build: ./jenkins
  volumes:
    - /data/jenkins/var/jenkins_home:/var/jenkins_home
  ports:
    - "80:8080"
    - "50000:50000"
  environment:
    - HOST_PATH=/data/jenkins
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
  extra_hosts:
    - "settings.simgroep.nl:10.39.18.108"

swarm-client-php56:
  build: ./swarm-client-php56
  volumes:
      - ./swarm-client-php56/php-conf.d:/php-conf.d
  extra_hosts:
    - "settings.simgroep.nl:10.39.18.108"

swarm-client-php70:
  build: ./swarm-client-php70
  volumes:
      - ./swarm-client-php70/php-conf.d:/php-conf.d
  extra_hosts:
    - "settings.simgroep.nl:10.39.18.108"

swarm-client-docker:
  build: ./swarm-client-docker
  extra_hosts:
    - "settings.simgroep.nl:10.39.18.108"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1
    - /usr/bin/docker:/usr/bin/docker
    - /workspace:/workspace
    - /data/composer/cache:/root/.composer/cache

registry:
  build: ./registry
  ports:
    - 8080:5000
  volumes:
    - /data/registry:/registry
  environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
