---
jenkins:
  build: ./jenkins
  volumes:
    - /data/jenkins/var/jenkins_home:/var/jenkins_home
  ports:
    - "80:8080"
    - "50000:50000"
  environment:
    - HOST_PATH=/data/jenkins
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry

swarm-client:
  build: ./swarm-client
  volumes:
      - ./swarm-client/php-conf.d:/php-conf.d

registry:
  build: ./registry
  ports:
    - 8080:5000
  volumes:
    - /data/registry:/registry
  environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
